# Generated by Django 4.2.15 on 2024-08-22 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='price',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='size',
        ),
    ]
