# Generated by Django 4.2.15 on 2024-09-05 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'price', 'verbose_name_plural': 'price'},
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_path',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='price',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='photos.photo'),
        ),
        migrations.AddIndex(
            model_name='photo',
            index=models.Index(fields=['photo_path'], name='photo_path_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['size', 'price'], name='price_size_70bf31_idx'),
        ),
        migrations.AddIndex(
            model_name='price',
            index=models.Index(fields=['size'], name='size_idx'),
        ),
    ]
