# Generated by Django 4.2.15 on 2024-09-05 12:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_alter_price_options_alter_photo_photo_path_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.photo'),
        ),
    ]
