# Generated by Django 4.2.15 on 2024-08-22 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price',
            old_name='photo_id',
            new_name='photo',
        ),
    ]
