# Generated by Django 4.2.15 on 2024-10-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_alter_price_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'price'},
        ),
        migrations.RemoveIndex(
            model_name='photo',
            name='photo_path_idx',
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='price_size_70bf31_idx',
        ),
        migrations.RemoveIndex(
            model_name='price',
            name='size_idx',
        ),
        migrations.AlterField(
            model_name='photo',
            name='photo_path',
            field=models.CharField(max_length=200),
        ),
    ]
